version: 0.2
env:
  variables:
    APP_NAME: "Add-notes"
phases:
  install:
    commands:
      - echo install process started
      - npm install && npm install -g @angular/cli
  build:
    commands:
      - echo build process started now
      - ng build --configuration=production
  post_build:
    commands:
      - echo build process finished
      - cd dist
      - ls -la
      - aws s3 sync . s3://codepipeline-ap-south-1 --delete